### ISSUE TITLE
How to flash board

### ISSUE THREAD

**Issue by hakanols** [nrf-rs/nrf9160-dk#1]
Tring to create an hex file to flash on my nRF9160-dk board. So far with no success.
Stolen some ideas from https://github.com/42-technology-ltd/nrf9160-demo/tree/use_latest_nrfxlib and
file https://github.com/42-technology-ltd/nrf9160-demo/blob/use_latest_nrfxlib/release.sh.
Tried to use ```arm-none-eabi-objcopy -O ihex $INPUT $OUTPUT_DIR/nrf9160dk.hex``` to create an hex file and then use that file to flash with the programmer in [nRF Connect](https://www.nordicsemi.com/Software-and-Tools/Development-Tools/nRF-Connect-for-desktop).
The board is successfully flashed but no COM printouts or LEDs blinks.
The hex file that arm-none-eabi-objcopy pops out is 1KB large and the input \target\thumbv8m.main-none-eabihf\debug\examples is on 1008KB large so something is probably wrong there.

Do you have any recommendation on how to flash on rust code to nNF9160-dk? Please update readme if you can.

**Comment by huntc** [comment]
Just came across this. Having the same issue. Were you able to overcome this?

**Comment by hakanols** [comment]
Sadly no.

**Comment by huntc** [comment]
> Sadly no.

I now have a draft PR that may help: https://github.com/nrf-rs/nrf9160-dk/pull/2

**Comment by hakanols** [comment]
Nice!
I will try it out. Perhaps during the weekend if Chronos is on my side.
